### ISSUE TITLE
Unreliable CTRL-C shutdown

### ISSUE THREAD

**Issue by bgottula** [seeing-things/track#111]
Got the following two errors on 20 Jan 2019 while attempting to quit. I think what happened is that I tried to use CTRL-C to shut down, but some thread or threads were still running and so I had to send CTRL-C a second time, which apparently worked but emitted this error. I suspect one of the threads is stalled for some reason and therefore doesn't terminate itself. There are four threads total: the main thread, two in the gamepad module, and one in the telem module. I am inclined to be a bit more suspicious of the telem module since I don't think it has been tested as extensively; I don't always enable it when testing indoors, for example.

```
rgottula@nix ~ $ optical_track 
Gamepad found and registered.
^CGoodbye!
^CException ignored in: <module 'threading' from '/usr/lib/python3.5/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 1288, in _shutdown
    t.join()
  File "/usr/lib/python3.5/threading.py", line 1054, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.5/threading.py", line 1070, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
```

A similar error in hybrid_track from the same night:
```
rgottula@nix ~ $ hybrid_track --meridian-side=east tle ~/Desktop/tles/SL16_RB.tle 
In TLE file mode: '/home/rgottula/Desktop/tles/SL16_RB.tle'.
Hybrid error source starting in blind tracking state
Gamepad found and registered.
Warning: loop filter update period was 0.2201 s, limit is 0.1000 s.
Warning: loop filter update period was 0.2201 s, limit is 0.1000 s.
^CGoodbye!
^CException ignored in: <module 'threading' from '/usr/lib/python3.5/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 1288, in _shutdown
    t.join()
  File "/usr/lib/python3.5/threading.py", line 1054, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.5/threading.py", line 1070, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
```

See also #118 which appears to be a duplicate of this.

**Comment by jgottula** [comment]
We did a bunch of debugging on this today to figure out what's going on. In the cases where we reproduced the issue, there were 2 threads still running: the main thread (which was using ~20% CPU and appeared to be actively issuing Gemini2 commands over the UDP socket), and another thread (which was not using any CPU, and had a call stack that indicated that it was probably a gamepad-related USB thread, waiting or possibly stuck in `poll`). Those stack traces are in the Slack DM's.

One thing worth revisiting would be the per-thread `strace` logs idea, which would help determine exactly which fd was being `poll`d upon by which thread and for how long, etc.

Also we might want to look into updating the Python inputs library from 0.1 (what we are using) to 0.5 (the latest), as it appears that a bunch of relatively recent development has gone into that, which may or may not help matters (as the gamepad code is one of the suspects here).

**Comment by jgottula** [comment]
Actually it's not necessarily a mystery as to why Gemini2 stuff was still happening in the main thread; the destructor for the `Gemini2` class calls the `stop_motion` method, which itself contains a `while True` loop that *could potentially* have problems if erroneous conditions cause it to never terminate. So that's worth investigating.

**Comment by bgottula** [comment]
We also discussed some options for ensuring that the mount motion stops even if other threads misbehave. The most promising idea is to explicitly call the destructor on the Mount object in the exception handler for `KeyboardInterrupt` so that it is called promptly, because otherwise it is not called until all other threads stop and the main thread finishes its cleanup processing (which may never happen if the process has to be terminated in some other way).

It may also be worth investigating adding handlers for other signals like SIGTERM.

**Comment by bgottula** [comment]
Okay. I think we may have solved the most pressing issue, which is that mount safing will occur without first waiting for the other threads to end. I'm going to close, but if we continue to encounter issues this could be reopened. We didn't really identify root cause or correct the problems preventing the other threads from ending.
