### ISSUE TITLE
Get location from GPS when available

### ISSUE THREAD

**Issue by bgottula** [seeing-things/track#131]
Add support for querying gpsd for location information obtained from a GPS receiver. This functionality should allow, at minimum:

- Retrieval of latitude, longitude, and altitude
- Retrieval of GPS receiver status and solution quality and confirmation that it meets some simple criteria. Examples: Does it have a fix? Is the error on the position estimate below some threshold?

I can think of a couple ways to integrate this into the main application code. In either case, GPS should be queried just once at app startup and then used from then on:
- Always query gpsd at startup. If the GPS solution is deemed to be good, use it, even if location info is provided as program arguments. If not, print a loud warning and fall back on the location provided as program arguments. This approach worries me a bit because we could miss such a warning.
- Use argument-supplied location information when provided in config file or on command line. Only query GPS when this is not provided. If GPS solution is bad, abort the program with a failure message. I think I like this option better because in practice we can *not* specify the location in the config file in the typical case, and then if GPS fails we can explicitly provide a location on the command line. Seems like this would leave fewer opportunities for unexpected behavior.

On the other hand, it might be a problem if the queried GPS location changes slightly from run to run, and especially between the value used during alignment and during tracking. So we may actually want to query the GPS location only during alignment and then store that info along with the mount model parameters.

Rationale: Observer location is currently given in a config file or on the command line. This works okay but it is easy to forget to update the location. This can lead to poor alignment and inaccurate pointing.

**Comment by jgottula** [comment]
We're now going to only query the GPS during alignment. It'll be a one-time thing, at the start of the alignment process, where we block for a period of time and get a GPS location, and then store that along with the other alignment crap in some serialized format that then goes on to get used by other stuff.

The way I'll implement this is to write a function that basically is "get me the lat/lon/alt please", which is blocking and which will keep reading the GPS until it gets a fix *and* is satisfied that it is a good fix. (Or until a timeout is reached, at which point it should most likely terminate with an error. Something like that.) This function will use the gpsd code that allows for continuously watching the gps device output via JSON responses that are automatically converted into dict-like objects. It will connect to the gps device; wait until it has a fix; wait until that fix is "suitably good" (TBD), and then disconnect from the gps device and return The Location which will be used for the alignment and all future observation stuff based on that alignment.

**Comment by jgottula** [comment]
http://manpages.ubuntu.com/manpages/bionic/man5/gpsd_json.5.html

**Comment by bgottula** [comment]
This feature has been implemented and some basic tests have passed. Programs that rely on a mount model will always get observer location via that model rather than from GPS or program arguments so that the observer location is consistent with the location used during alignment. For the align program and programs that do not use a mount model the location can either come from GPS if no program args are provided or if the lat, lon, and elevation program args are all provided they override GPS. It is an error when some but not all of lat, lon, and elevation are provided.
