### ISSUE TITLE
Fix webcam code so that it actually uses the enumeration methods to choose the pixel format and capture resolution

### ISSUE THREAD

**Issue by jgottula** [seeing-things/track#76]
Right now it does stuff that is frankly idiotic and which only just happens to produce sane results.

Ideally we want to use `_enum_pixel_formats` first and pick the best available pixfmt from there; and then run that through `_enum_frame_sizes` to pick the best resolution; and then in theory we'd run all of that through `_enum_frame_intervals` to pick the highest allowable framerate... except that the current webcam is too retarded to respond to the frame interval enumeration at all.

This should be fairly easy.

**Comment by bgottula** [comment]
Closing since we have retired the webcam from active use in our own setup, though the issue described was never addressed.
